config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api do
    post 'login', to: 'login#index'
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments
  has_many :posts, foreign_key: :author_id
  has_many :likes

  attribute :posts_counter, :integer, default: 0
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/views/users/index.html.erb
<main class="p-4">
  <% @users.each do |user| %>
    <%= link_to user_path(user.id), class: "user-link" do %>
      <section class="d-flex align-items-center border">
        <%= image_tag user.photo, :class => 'user-photo', alt: 'User photo' %>
        <div class="pl-2 flex-grow-1 d-flex justify-content-around align-items-center">
          <p class="fs-2"><%= user.name %></p>
          <p>Number of posts: <%= user.posts_counter%></p>
        </div>
      </section>
    <% end %>
  <% end %>
</main>

app/views/users/show.html.erb
<%= render "partials/error" %>
<section class="d-flex align-items-center">
  <%= image_tag @user.photo, :class => 'user-photo', alt: 'User photo' %>
  <div class="pl-2 flex-grow-1 d-flex justify-content-around align-items-center">
    <h2 class="fs-2"><%= @user.name %></h2>
    <p>Number of posts: <%= @user.posts_counter%></p>
  </div>
</section>
<section>
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</section>
 <div class="d-flex justify-content-end">
  <button type="button" class="btn btn-success mx-2"><%= link_to "Create Post", new_user_post_path(@user), { class: "user-link" } %></button>
  <button type="button" class="btn btn-info"><%= link_to "See all Posts", user_posts_path(@user.id), { class: "user-link" } %></button>
 </div>
<section>
  <% @posts.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id), class: "post-link" do %>
      <div class="container-fluid border">
        <h3><%= post.title %></h3>
        <p><%= post.text %></p>
        <p>Comments: <%= post.comments_counter.nil? ? 0 : post.comments_counter %></p>
        <p>Likes: <%= post.likes_counter.nil? ? 0 : post.likes_counter %></p>
      </div>
    <% end %>
  <% end %>
</section>