config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api do
    post 'login', to: 'login#index'
    resources :users, only: [:index] do
      resources :posts, only: [:index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User'

  after_save :update_post_counter
  after_destroy :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/posts_controller.rb
require 'jwt'
class Api::PostsController < Api::ApplicationController
  before_action :find_user
  def index
    if @user
      @posts = @user.posts.order(created_at: :asc)
      render json: @posts
    else
      render json: { status: 'Failure', error: 'Post Not Found' }
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @id = params[:user_id]
    @user = User.find(@id)
    @pagy, @posts = pagy(@user.posts.includes(comments: [:user]), items: 2)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes(comments: [:user]).find(params[:id])
    @like = Like.new
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @user = current_user
    @post = Post.new(
      author: @user,
      title: params[:title],
      text: params[:text],
      comments_counter: 0,
      likes_counter: 0
    )
    if @post.save
      flash[:success] = 'Post saved successfully.'
      redirect_to user_path(@user.id)
    else
      flash.now[:error] = 'Sorry something went wrong'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Friend deleted successfully!'
    else
      flash[:alert] = 'Failed to delete friend'
    end
    redirect_to users_path
  end
end

app/views/posts/index.html.erb
<section class="d-flex align-items-center">
  <%= image_tag @user.photo, :class => 'user-photo', alt: 'User photo' %>
  <div class="pl-2 flex-grow-1 d-flex justify-content-around align-items-center">
    <h2 class="fs-2"><%= @user.name %></h2>
    <p>Number of posts: <%= @user.posts_counter%></p>
  </div>
</section>
<div class="d-flex justify-content-end">
  <%== pagy_nav(@pagy) %>
</div>
<section>
  <% @posts.each do |post| %>
    <%= link_to user_post_path(@id, post.id), class: "user-link" do %>
      <div class="container-fluid border">
        <h3><%= post.title %></h3>
        <p><%= post.text %></p>
        <div class="d-flex justify-content-end">
          <p>Comments: <%= post.comments_counter.nil? ? 0 : post.comments_counter %></p>
          <p class="mx-2">Likes: <%= post.likes_counter.nil? ? 0 : post.likes_counter %></p>
        </div>
      </div>
    <% end %>
     <div class="container-fluid border">
        <% post.comments.each do |comment| %> 
          <div class="d-flex align-items-center">
            <h3><%= comment.user.name %></h3>:
            <h5 class="mx-2"><%= comment.text %></h5> 
          </div>   
        <% end %>
    </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "partials/error" %>

<%= form_with model: @post, url: user_posts_path(@user), local: true do |form| %>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, name: 'title', class: "form-control", required: true %>
  </div>
  <div class="field form-group">
    <%= form.label :text %>
    <%= form.text_area :text, name: 'text', class: "form-control", required: true %>
  </div>
  <br />
  <%= form.submit "Create Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<%= render "partials/error" %>

<div class="container-fluid border">
  <div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
      <h3><%= @post.title %></h3>
      <span class="mx-2">by <%= @user.name %></span>
    </div>
    <div class="d-flex ali">
      <p class="mx-3">Comments: <%= @post.comments_counter.nil? ? 0 : @post.comments_counter %></p>
      <p>Likes: <%= @post.likes_counter.nil? ? 0 : @post.likes_counter %></p>
    </div>
  </div>
  <p><%= @post.text %></p>
</div>
<div class="d-flex justify-content-end">
  <%= form_with model: @like, url: user_post_likes_path(@user, @post), scope: :like do |form|%>
     <%= form.submit 'Like post' %>
  <% end %>
  <button type="button" class="btn btn-success mx-2"><%= link_to "Comment", new_user_post_comment_path( post_id: @post.id), { class: "user-link" } %></button>
  <% if can? :destroy, @post %>
    <%= button_to "Delete Post", user_post_path(@user, @post), method: :delete, class: "btn btn-danger mx-2" %>
  <% end %>
</div>
<div class="container-fluid border">
  <% @post.comments.each do |comment| %> 
    <div class="d-flex align-items-center justify-content-between p-2">
      <div class="d-flex align-items-center">
        <h3><%= comment.user.name %></h3>:
        <h5 class="mx-2"><%= comment.text %></h5> 
      </div>
      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", user_post_comment_path(@user, @post, comment), method: :delete, class: "btn btn-danger mx-2" %>
      <% end %>
    </div>   
  <% end %>
</div>